services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=atyabtosif@gmail.com
      - N8N_BASIC_AUTH_PASSWORD=Unlock6767
    volumes:
      - ./n8ndata:/home/node/.n8n
      - ./rag_data:/data/rag_access
    restart: unless-stopped
